---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: cp-helm-provider-config-eks-prod
spec:
  credentials:
    source: Secret
    secretRef:
      name: kubectx-eks-workload-prod
      namespace: crossplane-system
      key: kubeconfig
