---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: ns-k8s-eks-prod
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          name: ns-k8s-eks-prod
  providerConfigRef:
    name: cp-k8s-provider-config-eks-prod  
